### ISSUE TITLE
Bubble Sort function is the optimised version

### ISSUE THREAD

**Issue by itzmk21** [FlakeyCheese/Compare-Sorting#1]
The bubble sort function is the optimised version using the flag. This means that by sorting with a bubble sort or the optimised bubble sort through the menu, it will always call the same function which is the optimised version.

**Comment by FlakeyCheese** [comment]
a rushed last minute feature not properly tested

**Comment by FlakeyCheese** [comment]
> The bubble sort function is the optimised version using the flag. This means that by sorting with a bubble sort or the optimised bubble sort through the menu, it will always call the same function which is the optimised version.

Just checked and I think you are wrong. The optimised flag is set only on option 5 otherwise it's false. When bubble sort is called it will only exit early if !swapped&&optimised . A concrete check of 10000 returned the optimised version a little quicker. 6479ms v 6404ms ---not much but the data is randomised and not all data sets benefit a great deal from this particular optimisation
